# Time in seconds a player will spawn an NPC if leaving after being hit
pvp_seconds_threshold: 30
# Time in seconds before the NPC despawns
despawn_seconds_threshold: 30
# If true, when being damaged, the despawn countdown will start over
reset_despawn_threshold: true
# Whether to set the player's vignette red when it would spawn an NPC if disconnecting
red_warning: false
# Disable spawning NPCs when the player is kicked by an operator
exempt_kicked: true
# Disable spawning NPCs when the player times out (e.g. connection failure or server freezing)
exempt_timed_out: true
# Disable spawning NPCs when the player is disconnected because of erroneous states (e.g. flying when disabled)
exempt_erroneous_state: false