# Time in seconds a player will spawn an NPC if leaving after being hit
pvp_seconds_threshold: 30
# Time in seconds before the NPC despawns
despawn_seconds_threshold: 30
# If true, when being damaged, the despawn countdown will start over
reset_despawn_threshold: true
# Whether to log when an NPC is spawned and despawned
logger: false
# Whether to set the player's vignette red when it would spawn an npc if disconnecting
red_warning: false