name: CowardlessPaper
version: '${version}'
main: code.blurone.cowardless.CowardlessPaper
api-version: '1.20'
authors: [ "BlurOne!" ]
scription: Replaces players who log out during combat with an NPC to be killed instead.
website: https://github.com/BlurOne-GIT/Cowardless